#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
import cv2
import numpy as np
from numpy import pi
from sensor_msgs.msg import LaserScan, Image
from cv_bridge import CvBridge, CvBridgeError
from geometry_msgs.msg import Twist, Point32, PolygonStamped, TransformStamped
from visualization_msgs.msg import Marker, MarkerArray
import tf2_ros
import time
import json
from std_msgs.msg import String

# Physical params
robot_length = 0.42
robot_width = 0.35
from_back_to_lidar = 0.39

# Behavior params
stop_dist = 0.5
avoid_length = 0.50  # 1.0
avoid_width = 0.75

#									Y
#									|					             								
#									|								 |<-avoid_length->|
#								|	|                   |<-stop_dist>|                .
#								|<-----robot_length---->|            .                .
#								|	|                   |            .                .
#	P---------------------------M	|					G-----------------------------I		<-
#	.			   .			|	|					|			 .				  .	     |
#	.			   L------------A___|___________________B------------E				  .      |
#	.			   .        	|	|		^			|  	 		 .				  .      |
#	.			   .	    	|   |		|			|            .                .      |
#	.			   .      		|   |		|			|      	     .				  .      |
#	.			   .    		|	|		|			|            .	              .      | avoid_width
#	.			   .  			|	|	robot_width		|	         .                .      |
#	S--------------W------------|---O-------------------|------------T----------------K------|------- X
#	.			   . 			|	|		|			|   	     .                .      |
#	.			   .    		|	|		|			|		     .                .      |
#	.			   .      		|	|		|			| 	         .                .      |
#	.			   .        	|	|		|			|            .                .      | 
#	.			   .		 	|	|		|			|            .                .      |
#	.			   R------------C___|_______V___________D------------F                .      |
#	.			   .			|	|					|            .                .      |
#	Q---------------------------N	|					H-----------------------------J     <-
#
# Robot's footprint is ABCD
# O is where the lidar is placing
# robot is facing forward on X-direction
# BDT and ACW are the STOP_ZONE

# AB is robot length
# BD is robot width
# AC_O is lidar offset from back side

AB = robot_length
BD = robot_width
AC_O = from_back_to_lidar

# Footprint coords
A = (-AC_O, robot_width / 2)
B = (robot_length - AC_O, robot_width / 2)
C = (-AC_O, -robot_width / 2)
D = (robot_length - AC_O, -robot_width / 2)

# Front Stop and Avoid zone coords
G = (robot_length - AC_O, avoid_width / 2)
H = (robot_length - AC_O, -avoid_width / 2)
E = (robot_length - AC_O + stop_dist, robot_width / 2)
F = (robot_length - AC_O + stop_dist, -robot_width / 2)
I = (robot_length - AC_O + stop_dist + avoid_length, avoid_width / 2)
J = (robot_length - AC_O + stop_dist + avoid_length, -avoid_width / 2)
T = (robot_length - AC_O + stop_dist, 0)
K = (robot_length - AC_O + stop_dist + avoid_length, 0)

# Back Stop and Avoid zone coords
M = (-AC_O, avoid_width / 2)
N = (-AC_O, -avoid_width / 2)
L = (-AC_O - stop_dist, robot_width / 2)
R = (-AC_O - stop_dist, -robot_width / 2)
P = (-AC_O - stop_dist - avoid_length, avoid_width / 2)
Q = (-AC_O - stop_dist - avoid_length, -avoid_width / 2)
W = (-AC_O - stop_dist, 0)
S = (-AC_O - stop_dist - avoid_length, 0)

## Stop zone of triangle shape
## Front
# slope and y-intercept of first quadrant
m1 = (T[1] - B[1]) / (T[0] - B[0])
b1 = B[1] - m1 * (B[0])
# slope and y-intercept of second quadrant
m2 = (T[1] - D[1]) / (T[0] - D[0])
b2 = D[1] - m2 * (D[0])

## Back
# slope and y-intercept of third quadrant
m3 = (A[1] - W[1]) / (A[0] - W[0])
b3 = A[1] - m3 * (A[0])
# slope and y-intercept of fourth quadrant
m4 = (C[1] - W[1]) / (C[0] - W[0])
b4 = C[1] - m4 * (C[0])

print("A", A)
print("B", B)
print("C", C)
print("D", D)
print("E", E)
print("F", F)
print("G", G)
print("H", H)
print("I", I)
print("J", J)
print("K", K)
print("L", L)
print("M", M)
print("N", N)
print("P", P)
print("Q", Q)
print("R", R)
print("S", S)
print("T", T)
print("W", W)

# quit()


class LineDetector(Node):

    def __init__(self):
        super().__init__('parallel_nav_node')
        self.subscription = self.create_subscription(
            LaserScan,
            '/scan',
            self.scan_callback,
            10)

        self.subscription = self.create_subscription(
            String,
            '/console_drive_msg',
            self.console_callback,
            10)

        self.image_pub = self.create_publisher(Image, 'image_topic', 10)

        self.bridge = CvBridge()

        self.cmd_vel_pub = self.create_publisher(Twist, '/diff_cont/cmd_vel_unstamped', 10)
        self.cmd_vel = Twist()

        self.foot_pub = self.create_publisher(PolygonStamped, "/footprint", 10)
        self.front_stop_pub = self.create_publisher(PolygonStamped, "/front_stop_zone", 10)
        self.back_stop_pub = self.create_publisher(PolygonStamped, "/back_stop_zone", 10)

        self.pg = PolygonStamped()
        self.pg_front_stop = PolygonStamped()
        self.pg_back_stop = PolygonStamped()

        self.br = tf2_ros.TransformBroadcaster(self)
        self.t = TransformStamped()

        ########################### Image Parameters ##########################
        ##### Frame size #####
        self.frame_width = 300
        self.frame_height = 600 

        self.frame_real_width = 2.0
        self.frame_real_height = 4.0

        ##### Blank map #####
        self._map = np.ones((self.frame_height, self.frame_width, 3), np.uint8) * 255
        self.amap = np.copy(self._map)

        ##### Line detection #####
        self.cannyMinVal = 50
        self.cannyMaxVal = 200
        self.houghThresh = 25
        self.houghMinLength = 10
        self.houghMaxGap = 150

        ##### Steering-adjusting zone on image #####
        self.lane_width_meter = 0.7
        self.half_lane_width_meter = self.lane_width_meter / 2.0
        self.half_lane_width_pixel = self.meter2pixel(self.half_lane_width_meter)

        self.frame_width_half = int(self.frame_width / 2)
        self.frame_height_half = int(self.frame_height / 2)

        self.x_mid_lane_MAX = int(self.frame_width_half) + self.half_lane_width_pixel / 1.2
        self.x_mid_lane_MIN = int(self.frame_width_half) - self.half_lane_width_pixel / 1.2
        self.center_offset_left = 3
        self.center_offset_right = 3
        self.center_min_DB = int(self.frame_width_half - self.center_offset_left)
        self.center_max_DB = int(self.frame_width_half + self.center_offset_right)

        self.center_thr_adj_min = int((self.x_mid_lane_MIN + self.center_min_DB) / 2) 
        self.center_thr_adj_max = int((self.x_mid_lane_MAX + self.center_max_DB) / 2) 

        ##### Rearrange and plotting #####
        self.left_line_list = []
        self.right_line_list = []
        self.y_L_dist = np.array([])
        self.y_R_dist = np.array([])

        ##### Mask #####
        ## Focus on front half frame
        focus_offset = 50
        self.front_vertices = np.array([[int(self.x_mid_lane_MIN - focus_offset), 0],
                                        [int(self.x_mid_lane_MIN - focus_offset), self.frame_height_half],
                                        [int(self.x_mid_lane_MAX + focus_offset), self.frame_height_half],
                                        [int(self.x_mid_lane_MAX + focus_offset), 0]], 
                                       np.int32)

        self.back_vertices = np.array([[int(self.x_mid_lane_MIN - focus_offset), self.frame_height_half],
                                       [int(self.x_mid_lane_MIN - focus_offset), self.frame_height],
                                       [int(self.x_mid_lane_MAX + focus_offset), self.frame_height],
                                       [int(self.x_mid_lane_MAX + focus_offset), self.frame_height_half]], 
                                      np.int32)

        self.sides_vertices = np.array([[int(self.x_mid_lane_MIN - focus_offset), 0],
                                         [int(self.x_mid_lane_MIN - focus_offset), self.frame_height],
                                         [int(self.x_mid_lane_MAX + focus_offset), self.frame_height],
                                         [int(self.x_mid_lane_MAX + focus_offset), 0]], 
                                        np.int32)

        ########################### Laser Scan Parameters ##########################
        self.angle_list = None
        self.range_list = None

        self.X = np.array([])
        self.Y = np.array([])

        self.PX = np.array([])
        self.PY = np.array([])

        ########################### Robot Parameters ##########################
        ########################### Filter Parameters ##########################
        self.line_list_length = 10
        self.steering_list_length = 10

        ##################### Robot Stop zone ########################
        self.FRONT_STOP = False
        self.BACK_STOP = False

        self.ROBOT_MODE = 'STOP'
        self.prev_ROBOT_MODE = self.ROBOT_MODE

        ##################### Console variables ########################
        self.CONSOLE_ARM = 0
        self.CONSOLE_MODE = 'STOP'

        ########################### Start ##########################
        self.run()

    def console_callback(self, msg):
        parse_data = json.loads(msg.data)

        self.CONSOLE_ARM = parse_data["ARM"]
        self.CONSOLE_MODE = parse_data["MODE"].encode("ascii", "ignore")

        if self.CONSOLE_MODE == 'FRONT':
            self.ROBOT_MODE = 'FRONT'
        elif self.CONSOLE_MODE == 'BACK':
            self.ROBOT_MODE = 'BACK'
        elif self.CONSOLE_MODE == 'STOP':
            self.ROBOT_MODE = 'STOP'
        else:
            self.ROBOT_MODE = 'STOP'

    def inFrontStopZone(self, x, y):
        if (B[0] < x) and (x < T[0]):
            if (D[1] < y) and (y < B[1]):
                y_cal1 = m1 * x + b1
                y_cal2 = m2 * x + b2
                if (y < y_cal1) and (y > y_cal2):
                    return True
                else:
                    return False
            else:
                return False
        else:
            return False

    def inBackStopZone(self, x, y):
        if (W[0] < x) and (x < A[0]):
            if (C[1] < y) and (y < A[1]):
                y_cal3 = m3 * x + b3
                y_cal4 = m4 * x + b4
                if (y < y_cal3) and (y > y_cal4):
                    return True
                else:
                    return False
            else:
                return False
        else:
            return False

    def send_velocity_command(self, linear_x, angular_z):
        self.cmd_vel.linear.x = linear_x
        self.cmd_vel.angular.z = angular_z
        self.cmd_vel_pub.publish(self.cmd_vel)

    def width_pixel2meter(self, width_px):
        width_meter = (self.frame_real_width * width_px) / self.frame_width
        return width_meter

    def meter2pixel(self, input_meter):
        output_pixel = (self.frame_width / self.frame_real_width) * input_meter
        return output_pixel

    def roi(self, img, vertices):
        # blank mask:
        mask = np.zeros_like(img)
        # fill the mask
        cv2.fillPoly(mask, [vertices], (255, 255, 255))
        # now only show the area that is the mask
        masked = cv2.bitwise_and(img, mask)
        return masked

    def map_with_limit(self, val, in_min, in_max, out_min, out_max):
        m = (out_max - out_min) / (in_max - in_min)
        out = m * (val - in_min) + out_min

        if out_min > out_max:
            if out > out_min:
                out = out_min
            elif out < out_max:
                out = out_max
        elif out_max > out_min:
            if out > out_max:
                out = out_max
            elif out < out_min:
                out = out_min

        return out

    def map(self, val, in_min, in_max, out_min, out_max):
        m = (out_max - out_min) / (in_max - in_min)
        out = m * (val - in_min) + out_min
        return out

    def scan_callback(self, msg):
        self.range_list = msg.ranges
        self.angle_list = np.arange((msg.angle_min), msg.angle_max, msg.angle_increment)

        ## using numpy array multiplication is much efficient than for loop each element
        self.X = np.multiply(self.range_list, np.cos(self.angle_list))
        self.Y = np.multiply(self.range_list, np.sin(self.angle_list))

        ## using numpy broadcasting to map X -> PY and to map Y -> PX
        self.PY = self.map(self.X, -(self.frame_real_height / 2), (self.frame_real_height / 2), self.frame_height, 0)
        self.PX = self.map(self.Y, -(self.frame_real_width / 2), (self.frame_real_width / 2), self.frame_width, 0)

        ## Use X and Y to check if there is point in front-stop-zone
        for i, (x, y) in enumerate(zip(self.X, self.Y)):
            if self.inFrontStopZone(x, y) and self.ROBOT_MODE == 'FRONT':
                self.FRONT_STOP = True
                self.ROBOT_MODE = 'BACK'
                break
            else:
                self.FRONT_STOP = False

            if self.inBackStopZone(x, y) and self.ROBOT_MODE == 'BACK':
                self.BACK_STOP = True
                break
            else:
                self.BACK_STOP = False

    def MovingAverage(self, data_raw, data_array, array_size):
        if len(data_array) < array_size:
            data_array = np.append(data_array, data_raw)
        else:
            data_array = np.delete(data_array, 0)
            data_array = np.append(data_array, data_raw)
        data_ave = np.average(data_array)
        return data_ave, data_array

    def image_bitmap(self, px, py):
        if 0 < px < self.frame_width:
            if 0 < py < self.frame_height:
                self.amap[py, px] = 0, 0, 0

    def run(self):
        self.timer = self.create_timer(0.05, self.run)  # 20 Hz

        steering_list = np.array([])
        x_min_list = np.array([])
        x_max_list = np.array([])
        y_min_list = np.array([])
        y_max_list = np.array([])

        m = 0.0
        last_front_stop_time = time.time()
        last_back_stop_time = time.time()

        while rclpy.ok():
            ## reset the list if the direction change
            if self.ROBOT_MODE != self.prev_ROBOT_MODE:
                x_min_list = np.array([])
                x_max_list = np.array([])
                y_min_list = np.array([])
                y_max_list = np.array([])
                steering_list = np.array([])

            if self.CONSOLE_ARM == 1:
                ## Use PX and PY to bitmap image
                for px, py in zip(self.PX, self.PY):
                    self.image_bitmap(int(px), int(py))

                ## Line detection
                processed_img = cv2.cvtColor(self.amap, cv2.COLOR_BGR2GRAY)
                processed_img = cv2.Canny(processed_img, self.cannyMinVal, self.cannyMaxVal)

                if (self.ROBOT_MODE == "FRONT") or (self.ROBOT_MODE == "BACK"):
                    processed_img = self.roi(processed_img, self.sides_vertices)
                    self.amap = self.roi(self.amap, self.sides_vertices)

                ## If HoughLineP can find line features on the image
                linesP = cv2.HoughLinesP(processed_img, 1, pi / 180, self.houghThresh, minLineLength=self.houghMinLength, maxLineGap=self.houghMaxGap)
                if linesP is not None:
                    slope = np.array([])

                    for i in range(len(linesP)):
                        l = linesP[i][0]
                        x1, y1, x2, y2 = l

                        ## Perfect vertical line
                        if (x1 == x2):
                            m = None
                            x = x1

                            if x < (self.frame_width / 2):
                                if y2 < y1:
                                    self.left_line_list.append([y2, y1, x2, x1])
                                else:
                                    self.left_line_list.append([y1, y2, x1, x2])
                            else:
                                if y2 < y1:
                                    self.right_line_list.append([y2, y1, x2, x1])
                                else:
                                    self.right_line_list.append([y1, y2, x1, x2])

                        else:
                            m = (float(y2) - float(y1)) / (float(x2) - float(x1))
                            x_ave = (x2 + x1) / 2.0
                            x = x_ave

                            ## Horizontal line with slope
                            if (abs(m) < 1) or (abs(m) > 15): 
                                pass

                            ## Vertical line with slope
                            else:
                                if x < (self.frame_width / 2):
                                    if y1 > y2:
                                        self.left_line_list.append([y2, y1, x2, x1])
                                    else:
                                        self.left_line_list.append([y1, y2, x1, x2])
                                else:
                                    if y1 > y2:
                                        self.right_line_list.append([y2, y1, x2, x1])
                                    else:
                                        self.right_line_list.append([y1, y2, x1, x2])

                else:
                    self.left_line_list = []
                    self.right_line_list = []
                    self.y_L_dist = np.array([])
                    self.y_R_dist = np.array([])

                ## Draw a circle at the middle of the image
                cv2.circle(self.amap, (self.frame_width_half, self.frame_height_half), 4, (0, 0, 0), -1)

                ## Find the best candidate line on each left and right side and plot
                ## Left line
                if len(self.left_line_list) > 0:
                    for left_line_elem in self.left_line_list:
                        self.y_L_dist = np.append(self.y_L_dist, (left_line_elem[1] - left_line_elem[0]))

                    idx_L = np.argmax(self.y_L_dist)

                    y_min_plot_L = self.left_line_list[idx_L][0]
                    y_max_plot_L = self.left_line_list[idx_L][1]
                    x_min_plot_L = self.left_line_list[idx_L][2]
                    x_max_plot_L = self.left_line_list[idx_L][3]

                    cv2.line(self.amap, (x_min_plot_L, y_min_plot_L), (x_max_plot_L, y_max_plot_L), (255, 0, 0), 1, cv2.LINE_AA)
                    x_mid_L = (x_min_plot_L + x_max_plot_L) / 2
                    y_mid_L = (y_min_plot_L + y_max_plot_L) / 2
                    self.y_L_dist = np.array([])
                else:
                    x_mid_L = 0

                ## Right line
                if len(self.right_line_list) > 0:
                    for right_line_elem in self.right_line_list:
                        self.y_R_dist = np.append(self.y_R_dist, (right_line_elem[1] - right_line_elem[0]))

                    idx_R = np.argmax(self.y_R_dist)

                    y_min_plot_R = self.right_line_list[idx_R][0]
                    y_max_plot_R = self.right_line_list[idx_R][1]
                    x_min_plot_R = self.right_line_list[idx_R][2]
                    x_max_plot_R = self.right_line_list[idx_R][3]
                    cv2.line(self.amap, (x_min_plot_R, y_min_plot_R), (x_max_plot_R, y_max_plot_R), (0, 255, 0), 1, cv2.LINE_AA)
                    x_mid_R = (x_min_plot_R + x_max_plot_R) / 2
                    y_mid_R = (y_min_plot_R + y_max_plot_R) / 2
                    self.y_R_dist = np.array([])
                else:
                    x_mid_R = 0

                ## If two lines of left and right sides are existing
                if x_mid_L != 0 and x_mid_R != 0:
                    x_min_plot_MID = (x_min_plot_L + x_min_plot_R) / 2
                    y_min_plot_MID = (y_min_plot_L + y_min_plot_R) / 2
                    x_max_plot_MID = (x_max_plot_L + x_max_plot_R) / 2
                    y_max_plot_MID = (y_max_plot_L + y_max_plot_R) / 2
                    case = "LR_"

                elif x_mid_L != 0 and x_mid_R == 0:
                    x_min_plot_MID = x_min_plot_L + self.half_lane_width_pixel
                    y_min_plot_MID = y_min_plot_L
                    x_max_plot_MID = x_max_plot_L + self.half_lane_width_pixel
                    y_max_plot_MID = y_max_plot_L
                    case = "L_"

                elif x_mid_L == 0 and x_mid_R != 0:
                    x_min_plot_MID = x_min_plot_R - self.half_lane_width_pixel
                    y_min_plot_MID = y_min_plot_R
                    x_max_plot_MID = x_max_plot_R - self.half_lane_width_pixel
                    y_max_plot_MID = y_max_plot_R
                    case = "R_"

                else:
                    angular_z = 0.0  # Pas de rotation
                    if self.ROBOT_MODE == "FRONT":
                        linear_x = 1.0  # Avancer
                    elif self.ROBOT_MODE == "BACK":
                        linear_x = -1.0  # Reculer
                    else:
                        linear_x = 0.0  # Arrêt

                    x_min_plot_MID = 0
                    case = "NO_"

                ## Care only if it found a line
                if case != "NO_":
                    x_min_plot_MID, x_min_list = self.MovingAverage(x_min_plot_MID, x_min_list, self.line_list_length)
                    x_max_plot_MID, x_max_list = self.MovingAverage(x_max_plot_MID, x_max_list, self.line_list_length)
                    y_min_plot_MID, y_min_list = self.MovingAverage(y_min_plot_MID, y_min_list, self.line_list_length)
                    y_max_plot_MID, y_max_list = self.MovingAverage(y_max_plot_MID, y_max_list, self.line_list_length)

                    cv2.line(self.amap, (int(x_min_plot_MID), int(y_min_plot_MID)), (int(x_max_plot_MID), int(y_max_plot_MID)), (0, 0, 255), 1, cv2.LINE_AA)
                    cv2.line(self.amap, (self.frame_width_half, int(y_min_plot_MID)), (self.frame_width_half, int(y_max_plot_MID)), (0, 0, 0), 1, cv2.LINE_AA)

                    if self.ROBOT_MODE == 'FRONT':
                        if (x_min_plot_MID < self.center_min_DB):
                            angular_z = self.map_with_limit(x_min_plot_MID, self.x_mid_lane_MIN, self.center_min_DB, 1.0, 0.5)
                            linear_x = self.map_with_limit(x_min_plot_MID, self.x_mid_lane_MIN, self.center_thr_adj_min, 0.5, 1.0)
                            case = case + "FWD_STR_L"
                        elif (x_min_plot_MID > self.center_max_DB):
                            angular_z = self.map_with_limit(x_min_plot_MID, self.center_max_DB, self.x_mid_lane_MAX, -0.5, -1.0)
                            linear_x = self.map_with_limit(x_min_plot_MID, self.center_thr_adj_max, self.x_mid_lane_MAX, 1.0, 0.5)
                            case = case + "FWD_STR_R"
                        else:
                            angular_z = 0.0
                            linear_x = 1.0
                            case = case + "FWD_THR"

                    elif self.ROBOT_MODE == 'BACK':
                        if (x_max_plot_MID < self.center_min_DB):
                            angular_z = self.map_with_limit(x_max_plot_MID, self.x_mid_lane_MIN, self.center_min_DB, -1.0, -0.5)
                            linear_x = self.map_with_limit(x_max_plot_MID, self.x_mid_lane_MIN, self.center_thr_adj_min, -0.5, -1.0)
                            case = case + "BWD_STR_L"
                        elif (x_max_plot_MID > self.center_max_DB):
                            angular_z = self.map_with_limit(x_max_plot_MID, self.center_max_DB, self.x_mid_lane_MAX, 0.5, 1.0)
                            linear_x = self.map_with_limit(x_max_plot_MID, self.center_thr_adj_max, self.x_mid_lane_MAX, -1.0, -0.5)
                            case = case + "BWD_STR_R"
                        else:
                            angular_z = 0.0
                            linear_x = -1.0
                            case = case + "BWD_THR"

                    else:
                        angular_z = 0.0
                        linear_x = 0.0

                cv2.circle(self.amap, (int(self.x_mid_lane_MIN), 0), 3, (255, 0, 0), -1)
                cv2.circle(self.amap, (int(self.x_mid_lane_MAX), 0), 3, (0, 255, 0), -1)
                cv2.circle(self.amap, (int(self.center_min_DB), 0), 3, (255, 255, 0), -1)
                cv2.circle(self.amap, (int(self.center_max_DB), 0), 3, (0, 255, 255), -1)
                cv2.circle(self.amap, (int(self.center_thr_adj_min), 0), 3, (0, 100, 255), -1)
                cv2.circle(self.amap, (int(self.center_thr_adj_max), 0), 3, (100, 0, 255), -1)

                cv2.circle(self.amap, (int(self.x_mid_lane_MIN), self.frame_height), 3, (255, 0, 0), -1)
                cv2.circle(self.amap, (int(self.x_mid_lane_MAX), self.frame_height), 3, (0, 255, 0), -1)
                cv2.circle(self.amap, (int(self.center_min_DB), self.frame_height), 3, (255, 255, 0), -1)
                cv2.circle(self.amap, (int(self.center_max_DB), self.frame_height), 3, (0, 255, 255), -1)
                cv2.circle(self.amap, (int(self.center_thr_adj_min), self.frame_height), 3, (0, 100, 255), -1)
                cv2.circle(self.amap, (int(self.center_thr_adj_max), self.frame_height), 3, (100, 0, 255), -1)

                if self.FRONT_STOP or self.BACK_STOP:
                    angular_z = 0.0  # Pas de rotation
                    linear_x = 0.0  # Arrêt

                self.send_velocity_command(linear_x, angular_z)
                print("case: %s x_min_plot_MID: %d , linear_x: %.2f, angular_z: %.2f" % (case, x_min_plot_MID, linear_x, angular_z))

                # clear list out
                self.left_line_list = []
                self.right_line_list = []

                ## publish image topic
                try:
                    image_message = self.bridge.cv2_to_imgmsg(self.amap, encoding="bgr8")  # bgr8 #8UC1
                    self.image_pub.publish(image_message)
                except CvBridgeError as e:
                    print(e)

                self.amap = np.copy(self._map)
                processed_img = np.copy(self._map)

        else:
            self.cmd_vel.linear.x = 0.0
            self.cmd_vel.angular.z = 0.0

        ## Drawing Polygons ##
        # footprint
        self.pg.header.stamp = self.get_clock().now().to_msg()
        self.pg.header.frame_id = "base_footprint"
        self.pg.polygon.points = [
            Point32(x=A[0], y=A[1]),
            Point32(x=B[0], y=B[1]),
            Point32(x=D[0], y=D[1]),
            Point32(x=C[0], y=C[1])]

        # front stop zone
        self.pg_front_stop.header.stamp = self.get_clock().now().to_msg()
        self.pg_front_stop.header.frame_id = "base_footprint"
        self.pg_front_stop.polygon.points = [
            Point32(x=B[0], y=B[1]),
            Point32(x=T[0], y=T[1]),
            Point32(x=D[0], y=D[1]),
            Point32(x=B[0], y=B[1])]

        # back stop zone
        self.pg_back_stop.header.stamp = self.get_clock().now().to_msg()
        self.pg_back_stop.header.frame_id = "base_footprint"
        self.pg_back_stop.polygon.points = [
            Point32(x=A[0], y=A[1]),
            Point32(x=C[0], y=C[1]),
            Point32(x=W[0], y=W[1]),
            Point32(x=A[0], y=A[1])]

        # construct tf
        self.t.header.frame_id = "base_footprint" 
        self.t.header.stamp = self.get_clock().now().to_msg()
        self.t.child_frame_id = "base_link"
        self.t.transform.translation.x = 0.0
        self.t.transform.translation.y = 0.0
        self.t.transform.translation.z = 0.0

        self.t.transform.rotation.x = 0.0
        self.t.transform.rotation.y = 0.0
        self.t.transform.rotation.z = 0.0
        self.t.transform.rotation.w = 1.0
        self.br.sendTransform(self.t)

                # Publish the footprint and stop zones
        self.foot_pub.publish(self.pg)
        self.front_stop_pub.publish(self.pg_front_stop)
        self.back_stop_pub.publish(self.pg_back_stop)

        self.prev_ROBOT_MODE = self.ROBOT_MODE

        self.cmd_vel_pub.publish(self.cmd_vel)


def main(args=None):
    rclpy.init(args=args)
    line_detector = LineDetector()
    rclpy.spin(line_detector)
    line_detector.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()